Indenting.

diff --git a/triplew b/triplew
--- a/triplew
+++ b/triplew
@@ -25,97 +25,97 @@ ___________      .__       .__           _________
 
 EOF
 function command_exists () {
-    type "$1" &> /dev/null ;
+  type "$1" &> /dev/null ;
 }
 function _spinner() {
-    # $1 start/stop
-    #
-    # on start: $2 display message
-    # on stop : $2 process exit status
-    #           $3 spinner function pid (supplied from stop_spinner)
+  # $1 start/stop
+  #
+  # on start: $2 display message
+  # on stop : $2 process exit status
+  #           $3 spinner function pid (supplied from stop_spinner)
 
-    local on_success="DONE"
-    local on_fail="FAIL"
-    local green="\e[1;32m"
-    local red="\e[1;31m"
-    local nc="\e[0m"
+  local on_success="DONE"
+  local on_fail="FAIL"
+  local green="\e[1;32m"
+  local red="\e[1;31m"
+  local nc="\e[0m"
 
-    case $1 in
-        start)
-            # calculate the column where spinner and status msg will be displayed
-            let column=$(tput cols)-${#2}-8
-            # display message and position the cursor in $column column
-            echo -ne "${2}"
-            printf "%${column}s"
+  case $1 in
+    start)
+    # calculate the column where spinner and status msg will be displayed
+    let column=$(tput cols)-${#2}-8
+    # display message and position the cursor in $column column
+    echo -ne "${2}"
+    printf "%${column}s"
 
-            # start spinner
-            i=1
-            sp='\|/-'
-            delay=${SPINNER_DELAY:-0.15}
+    # start spinner
+    i=1
+    sp='\|/-'
+    delay=${SPINNER_DELAY:-0.15}
 
-            while :
-            do
-                printf "\b${sp:i++%${#sp}:1}"
-                sleep "$delay"
-            done
-            ;;
-        stop)
-            if [[ -z ${3} ]]; then
-                echo "spinner is not running.."
-                exit 1
-            fi
+    while :
+    do
+      printf "\b${sp:i++%${#sp}:1}"
+      sleep "$delay"
+    done
+    ;;
+    stop)
+    if [[ -z ${3} ]]; then
+      echo "spinner is not running.."
+      exit 1
+    fi
 
-            kill "$3" > /dev/null 2>&1
+    kill "$3" > /dev/null 2>&1
 
-            # inform the user uppon success or failure
-            echo -en "\b["
-            if [[ $2 -eq 0 ]]; then
-                echo -en "${green}${on_success}${nc}"
-            else
-                echo -en "${red}${on_fail}${nc}"
-            fi
-            echo -e "]"
-            ;;
-        *)
-            echo "invalid argument, try {start/stop}"
-            exit 1
-            ;;
-    esac
+    # inform the user uppon success or failure
+    echo -en "\b["
+    if [[ $2 -eq 0 ]]; then
+      echo -en "${green}${on_success}${nc}"
+    else
+      echo -en "${red}${on_fail}${nc}"
+    fi
+    echo -e "]"
+    ;;
+    *)
+    echo "invalid argument, try {start/stop}"
+    exit 1
+    ;;
+  esac
 }
 
 function start_spinner {
-    # $1 : msg to display
-    _spinner "start" "${1}" &
-    # set global spinner pid
-    _sp_pid=$!
-    disown
+  # $1 : msg to display
+  _spinner "start" "${1}" &
+  # set global spinner pid
+  _sp_pid=$!
+  disown
 }
 
 function stop_spinner {
-    # $1 : command exit status
-    _spinner "stop" "$1" $_sp_pid
-    unset _sp_pid
+  # $1 : command exit status
+  _spinner "stop" "$1" $_sp_pid
+  unset _sp_pid
 }
 
 function encrypt
 {
-    start_spinner Encrypting file, please wait...
-    ENCFILE="$FILE.triple"
-    cat "$FILE" | triplesec -b enc -k $KEY > $ENCFILE
-    stop_spinner $?
-    echo -e "${COL_GREEN}Your encrypted file has been saved to ${COL_CYAN}$FILE.triple $COL_RESET"
+  start_spinner Encrypting file, please wait...
+  ENCFILE="$FILE.triple"
+  cat "$FILE" | triplesec -b enc -k $KEY > $ENCFILE
+  stop_spinner $?
+  echo -e "${COL_GREEN}Your encrypted file has been saved to ${COL_CYAN}$FILE.triple $COL_RESET"
 }
 function decrypt
 {
-    if [ "$EXT" == "triple" ];
-    then
-      start_spinner Decrypting file, please wait...
-      cat "$FILE" | triplesec -b dec -k "$KEY" > "$BASE"
-      stop_spinner $?
-      echo -e "${COL_GREEN}Your decrypted file has been saved to ${COL_CYAN}$BASE. $COL_RESET"
-    else
-      echo -e "${COL_RED}The file doesn't have a .triple extension.s $COL_RESET"
-    fi
+  if [ "$EXT" == "triple" ];
+  then
+    start_spinner Decrypting file, please wait...
+    cat "$FILE" | triplesec -b dec -k "$KEY" > "$BASE"
+    stop_spinner $?
+    echo -e "${COL_GREEN}Your decrypted file has been saved to ${COL_CYAN}$BASE. $COL_RESET"
+  else
+    echo -e "${COL_RED}The file doesn't have a .triple extension.s $COL_RESET"
+  fi
 }
 if command_exists triplesec ;
 then
